### ISSUE TITLE
Fatal error calling DevicesController.claimNetworkDevices

### ISSUE THREAD

**Issue by dowlingw** [meraki/meraki-node-sdk#1]
# Description
Using `meraki-node-sdk` generates a fatal error when calling `DevicesController.claimNetworkDevices`.

This appears to be because the API is specified in meraki/openapi as returning an HTTP 200 for this request, even though the actual API behaviour returns no response payload (should be HTTP 204 in that case).

# Environment
meraki 1.1.0
nodejs v10.16.2
npm 6.9.0
Windows 10 Enterprise build 17134

# Expected Behavior
The promise returned by `DevicesController.claimNetworkDevices` to resolve following a successful request to the Meraki Dashboard API.

# Actual Behavior
The request is processed successfully by the remote server, however the Meraki SDK raises a fatal error that is not able to be caught by calling code, causing the application to terminate.

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _request (C:\Users\username\git\repository\node_modules\meraki\lib\Controllers\DevicesController.js:309:41)
    at Request.cb [as _callback] (C:\Users\username\git\repository\node_modules\meraki\lib\Http\Client\RequestClient.js:79:9)
    at Request.self.callback (C:\Users\username\git\repository\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\username\git\repository\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (C:\Users\username\git\repository\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
```

**Comment by dowlingw** [comment]
The offending code is in the APImatic generated code for the `DevicesController` which is attempting to invoke `JSON.parse` on an empty response.

![image](https://user-images.githubusercontent.com/1167455/65400844-1d50b580-ddf7-11e9-9d03-4dc7290eba66.png)

**Comment by dowlingw** [comment]
The realistic fix for this issue is likely:
1. Update the API behavior to return HTTP 204; and
2. Update the OpenAPI specification at https://github.com/meraki/openapi and regenerate the SDK

**Comment by dexterlabora** [comment]
Thanks for the detailed bug report. 

- The API will soon have a major update, going from v0 to v1, where the status codes and response bodies are being improved. These are technically "breaking changes", thus these issues have been gathered up for the next major release.
- There is an open issue with APImatic to resolve the SDK problem, for future minor updates to v0.

**Comment by dexterlabora** [comment]
This has been fixed in the September release.

https://github.com/meraki/meraki-node-sdk/blob/a327f1bce7129066903ee924fd56f3c54571475e/lib/Controllers/DevicesController.js#L145-L147
